### ISSUE TITLE
Setting DB schema name for Job Repository that is different from the DB login user

### ISSUE THREAD

**Issue by gabor5** [longwa/grails-spring-batch#12]
Environment:
- GGTS Version: 3.1.0.RELEASE (Build Id: 201210061306)
- Grails 2.1.1
- Spring Batch Core 2.1.8
- Spring Batch Admin 1.2.1
- Spring Batch Grails Plugin 1.0.RC1 
- Windows 7 x64

When the Job Repository is in a DB2 schema with a name that is different from the Database
login user name, SrpringBatch plugin UI tries to access the repository in the wrong
(non-existing) schema, triggering the following exception in the jobService: 
com.ibm.db2.jcc.a.SqlExceptionMessage:"DB2LOAD.BATCH_JOB_INSTANCE" is an
undefined name (also SqlException: "DB2LOAD.BATCH_STEP_EXECUTION_CONTEXT, 
despite using the tablePrefix = "DB2ADMIN.BATCH")

This may not be specific to DB2.

Config.groovy configuration:
  plugin {
    springBatch { 

```
  database = "db2" 
  tablePrefix = "DB2ADMIN.BATCH"   // this does not appear to set the schema to DB2ADMIN
  loadTables = true
}
```

  }

DataSource configuration:
  dataSource { 
    username = "db2load" 
  } 
  hibernate.default_schema = 'DB2ADMIN'   // this is what I would like

The hibernate setting is actually successful but ineffective since Spring Batch Admin (jobService)
uses JDBC with embedded SQL.
## Work-around:

Got the Spring Batch Gails Plugin UI part working with loadTables = false setting, 
along with tablePrefix direct injection into the jobService, jobRepository, and jobExplorer, as shown below.

  plugin {
    springBatch { 
      loadTables = false  // to avoid startup time 'SqlException: "DB2LOAD.BATCH_STEP_EXECUTION_CONTEXT" is an undefined name' 
    }
  }

And in the conf/spring/resources.groovy:

// Place your Spring DSL code here
beans = {
  jobService(org.springframework.batch.admin.service.SimpleJobServiceFactoryBean) { bean ->

```
jobRepository = ref('jobRepository')
jobLauncher = ref('jobLauncher')
jobLocator = ref('jobRegistry')
dataSource = ref('dataSource')
tablePrefix = "DB2ADMIN.BATCH_"
```

  }

  jobRepository(org.springframework.batch.core.repository.support.JobRepositoryFactoryBean) { bean ->

```
dataSource = ref('dataSource')
transactionManager = ref('transactionManager')
databaseType = "DB2"
tablePrefix = "DB2ADMIN.BATCH_"
isolationLevelForCreate = "ISOLATION_DEFAULT"
```

  }

  jobExplorer(org.springframework.batch.core.explore.support.JobExplorerFactoryBean) { bean ->

```
dataSource = ref('dataSource')
tablePrefix = "DB2ADMIN.BATCH_"
```

  }
}

**Comment by dpcolumbus** [comment]
it worked for me with tablePrefix = "DB2ADMIN.BATCH_"

	 <bean id="jobRepository"
		class="org.springframework.batch.core.repository.support.JobRepositoryFactoryBean">
		<property name="dataSource" ref="dataSource" />
		<property name="transactionManager" ref="transactionManager" />
		<property name="databaseType" value="SQLSERVER" />
		<property name="tablePrefix" value="batch.BATCH_"></property>
	</bean>
