### ISSUE TITLE
Transfer ownership of this repository to me (@longwa)

### ISSUE THREAD

**Issue by longwa** [longwa/grails-spring-batch#32]
Hi John,
I've been maintaining and enhancing my own fork of this for a couple of years now for our project. I plan on upgrading it to support Grails 3 soon and will probably maintain it going forward.

If you want to transfer this repository to me, I will take over maintenance officially going forward.

I maintain the build-test-data plugin as well as a few other smaller ones that I wrote.

Rgds,
Aaron

**Comment by johnrengelman** [comment]
Sounds great. Transferring it now. I don't believe @danieldbower is maintaining this anymore either (at least I haven't seen a commit in quite a while).

**Comment by johnrengelman** [comment]
I can't transfer this repo to you, as you already have a repo named `grails-spring-batch`. Can you rename that one, so I can transfer you ownership of this one?

**Comment by longwa** [comment]
Oops, sorry, I renamed my fork just now.

Once it's done I'll publish a new Grails 2.x version that adds my changes
and updates the SCM url to point to the new repo location.

Thanks,
Aaron

**Comment by danieldbower** [comment]
I ended up making a bunch of breaking changes here:  https://github.com/infinumllc/grails-spring-batch .  Since they were breaking, I ended up not pushing them back to this master.  Some useful stuff in there if you're interested @longwa

**Comment by longwa** [comment]
@danieldbower Thanks, I'll definitely take a look. For the most part, I've just been keeping the Spring Batch version up to date as well as fixed a couple of config dev reloading issues so that live changes work.

We are moving our project to Grails 3 in the next month so I'll definitely make that upgrade soon.

**Comment by johnrengelman** [comment]
Hmmm, Github still won't let me move it:

> longwa already has a repository in the johnrengelman/grails-spring-batch network

**Comment by longwa** [comment]
Just making sure the GitHub guys are doing all their validations, lol.

I've deleted my fork, please try again when you get a chance.

Thanks,
Aaron

**Comment by johnrengelman** [comment]
The transfer has been initiated.
